version: 2.1
orbs:
  twistcli: twistlock/twistcli-scan@1.0.4
jobs:
  docker-build-and-save:
    executor: twistcli/default
    steps:
      - checkout
      - run: 
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t cdjg35/kubecost:$TAG .
      - run: mkdir -p workspace
      - run: 'docker save cdjg35/kubecost:$TAG -o workspace/image.tar'
      - persist_to_workspace:
          root: workspace
          paths:
            - image.tar
workflows:
  scan-image:
    jobs: 
      TAG=0.1.$CIRCLE_BUILD_NUM
      - docker-build-and-save
      - twistcli/scan-image:
          requires:
            - docker-build-and-save
          context: tl_scan_context
          image: 'cdjg35/kubecost:$TAG'
          imagetar: image.tar
          vuln-thresh: critical
          comp-thresh: ''
          only-fixed: true