version: 2
orbs:
  anchore-engine: anchore/anchore-engine@1.0.0
jobs:                 
  build:
    machine: true
    steps:
      - checkout
      - run: | 
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t cdjg35/kubecost-cost-model:$TAG .
          docker push cdjg35/kubecost-cost-model:$TAG
  deploy:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t cdjg35/kubecost-cost-model:latest .
          docker push cdjg35/kubecost-cost-model:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires: 
            - build
          filters:
            branches:
              only:
                - master
  scan_image:
    jobs:
      - anchore/image_scan:
          image_name: anchore/anchore-engine:latest
          timeout: '300'
          private_registry: True
          registry_name: docker.io
          registry_user: "${DOCKER_USER}"
          registry_pass: "${DOCKER_PASS}"
