version: 2.1
orbs:
  anchore-engine: anchore/anchore-engine@1.5.0
jobs:
  scan:
    executor: anchore/anchore_engine
    steps:
      - setup_remote_docker
      - checkout
      - run: | 
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t cdjg35/kubecost-cost-model:$TAG .
          docker push cdjg35/kubecost-cost-model:$TAG
      - anchore/analyze_local_image:
          dockerfile_path: ./Dockerfile
          image_name: ecdjg35/kubecost-cost-model:$TAG
          policy_bundle_file_path: .circleci/.anchore/policy_bundle.json
          policy_failure: true
          timeout: '500'
      - anchore/parse_reports
      - store_artifacts:
          path: anchore-reports    
  build:
    machine: true
    steps:
      - checkout
      - run: | 
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t cdjg35/kubecost-cost-model:$TAG .
          docker push cdjg35/kubecost-cost-model:$TAG
  deploy:
    machine: true
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t cdjg35/kubecost-cost-model:latest .
          docker push cdjg35/kubecost-cost-model:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - scan
      - deploy:
          requires: 
            - build
          filters:
            branches:
              only:
                - master